6 - W25QXX SPI model class initial version
stasOR4ik/SpiFlash pull request #10
Opened 2019-03-26 20:54 UTC by stasOR4ik

2019-03-27 09:12 UTC, krucios requested changes

2019-03-27 09:12 UTC, krucios commented on spi_flash_component.sv
> +import uvm_pkg::*;
Нужно упаковать класс модели в пакет.
Пакет должен быть описан в отдельном файле, а файл с моделью должен инклюдиться в файл пакета.

2019-03-27 09:12 UTC, krucios commented on spi_flash_component.sv
> +import uvm_pkg::*;
Соответственно, импорт uvm пакета и инклюд макросов должен быть в файле пакета модуля

2019-03-27 09:15 UTC, stasOR4ik commented on spi_flash_component.sv
> +import uvm_pkg::*;
Может у вас найдётся ссылка на статью или пример данного подхода?

2019-03-27 11:13 UTC, krucios commented on spi_flash_component.sv
> +import uvm_pkg::*;
https://www.chipverify.com/systemverilog/systemverilog-package
http://www.asic-world.com/systemverilog/hierarchy1.html

Организовать все файлы, относящиеся к модели памяти в отдельный пакет - это хорошая идея, т.к. это дает возможность логически структурировать ваш тестбенч. Более того, компилятору легче будет понимать, какие части тестбенча нужно перекомпиливать после очередных изменений.

2019-03-27 11:14 UTC, krucios commented on spi_flash_component.sv
> +import uvm_pkg::*;
https://github.com/imokanj/gpio_agent/blob/master/src/gpio_agent_pkg.sv

Вот тут еще проект с примером организаации файлов агента в пакет

2019-04-13 11:58 UTC, krucios commented
Alles gut!

2019-04-13 11:59 UTC, krucios approved these changes

2019-04-13 11:59 UTC, merged