3 - SPI driver class(adding logic for sequencer)
stasOR4ik/SpiFlash pull request #13
Opened 2019-05-21 21:21 UTC by ArsenyZhivitsky

3 - SPI driver class(adding logic for sequencer)

2019-05-22 21:02 UTC, krucios requested changes
Почти правильно :)
Вам нужно использовать число 8 в цикле или оператор "меньше либо равно", т.к. В байте 8 бит.
Вам нужно использовать сигнал do интерфейс, а не Di. Di является входным, а do выходным сигналом.
Хендлер req - это не массив, а объект. Оператор [] к нему просто так не может быть применен. Скорее всего, подразумевалось req.data[I]

2019-05-23 19:38 UTC, krucios approved these changes

2019-05-23 19:44 UTC, krucios requested changes
имя сигнала в интерфейсе, которое нужно было использовать: o_do, а не i_d0
После того, как кпоследний бит отправлен на провод o_do, нужно еще подождать posedge vif.i_clk. Это позволит "подержать" этот бит на проводе в течении одного такта

2019-05-24 13:30 UTC, stasOR4ik commented
> имя сигнала в интерфейсе, которое нужно было использовать: o_do, а не i_d0
> После того, как кпоследний бит отправлен на провод o_do, нужно еще подождать posedge vif.i_clk. Это позволит "подержать" этот бит на проводе в течении одного такта

В спецификации не сказано, что нужно держать последний бит, там сразу идёт 1 бит нового байта

2019-05-27 18:40 UTC, krucios commented
> 
> 
> > имя сигнала в интерфейсе, которое нужно было использовать: o_do, а не i_d0
> > После того, как кпоследний бит отправлен на провод o_do, нужно еще подождать posedge vif.i_clk. Это позволит "подержать" этот бит на проводе в течении одного такта
> 
> В спецификации не сказано, что нужно держать последний бит, там сразу идёт 1 бит нового байта

Не нужно удерживать его более одного такта, но один такт он точно должен продержаться на шине. В противном случае, приемник просто не сможет его словить и получится, что Вы передали 7 бит вместо 8.

Но Вы правы в том, что ничего менять не нужно :) Перед отправкой первого бита следующей транзакции драйвер попадет на конструкцию
`@(posedge vif.i_clk);`
и честно подождет следующего клока.

Итого, с логикой ничего менять не нужно, а вот имя сигнала все же стоит поправить.

2019-06-03 19:45 UTC, krucios approved these changes

2019-06-03 19:45 UTC, merged